In [6]:
import pandas as pd
from sklearn.linear_model import ElasticNet
#from sklearn.model_selection import KFold
from sklearn import preprocessing
import numpy as np


In [16]:
#df = pd.read_csv("../../data/csv/depression_2017/real/test_eRisk_depression_2017_1.csv")
df = pd.read_csv("/projets/depression/eRisk_data/modified_by_faneva/csv/depression_2017/real/train_eRisk_depression_2017.csv")
cols = df.columns
total_cols = len(cols)
#print (total_cols)
features_df = df.iloc[:,1:(total_cols-1)]
X = features_df.to_numpy()
#print (len(X))
class_label = df.iloc[:,total_cols-1].to_numpy()
#print (class_label)
y = [1 if y is 'p' else 0 for y in class_label]

regr = ElasticNet(random_state=0)
#scaler = preprocessing.StandardScaler().fit(X)
#scaler = preprocessing.MinMaxScaler()
scaler = preprocessing.PowerTransformer(method='box-cox', standardize=False)
print (X)
print (np.nanmin(X))

X_scaled = scaler.fit_transform(X)
print (X_scaled)
#regr.fit(X_scaled, y)
#print(regr.coef_)
#print(regr.intercept_)

[[0.004101 0.008434 0.008937 ... 0.110732 0.976983 0.964331]
 [0.009185 0.009185 0.013777 ... 0.       1.       0.      ]
 [0.012346 0.004938 0.       ... 0.389533 0.353812 0.964401]
 ...
 [0.011389 0.007217 0.001353 ... 0.155998 0.357368 0.997364]
 [0.007115 0.006468 0.003234 ... 0.147474 0.09849  0.980609]
 [0.009032 0.011097 0.002194 ... 0.204328 0.867957 0.985356]]


NameError: name 'np' is not defined

In [20]:
#defining groups
g1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]
g2 = [19,20,21,22]
g3 = [45,48,49]
g4 = [47]
g5 = [58]
g6 = [43,46]
g7 = [50,253,254,255,256]
g8 = [41,42,44]
g9 = [27,28,29,30,31]
g10 = [54,55,56,57]
g11 = [32,33,34,35,36,37,38,39]
g12 = [40]
g13 = [23]
g14 = [24,26,53]
g15 = [25,51,52]
g16 = [59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252]
groups = [g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14,g15,g16]
#groups

In [29]:
#defining meta groups
#meta group
#5 meta-groups

#meta1 -representation of the text\\
#I bow
#II POS
#XII n-gram\\ [this could be a mistake]
meta1 = g1 + g2 + g3

#meta2- lexicons on depression\\
#XI depress 
#X drung 
#XIV Sleepy\\
meta2 = g4 + g5 + g6

#meta3- temporality\\
#VI time
#IX past\\
meta3 = g7 + g8

#meta4- writing style \fr{C'est quoi?} \jm{la réthorique}\\
#V averages
#XV readibility
#VII first pers
#VIII overgenralization
#III neg
#IV cap\\
meta4 = g9 + g10 + g11 + g12 + g13 + g14

#meta5- emotion \\
#XIII emoticon, sentiment
#XVI empath
meta5 = g15 + g16


meta1 = g1 + g2 + g3
meta2 = g4 + g5 + g6
meta3 = g7 + g8
meta4 = g9 + g10 + g11 + g12 + g13 + g14
meta5 = g15 + g16

#print (df.head())
print (len(meta1))
print (df.columns)
train = df.filter(df.columns[[0] + meta1 + [257]],axis=1)

print (len(train.columns))
#print (df.columns)
train

25
Index(['uid', 'unigram_im_frequency', 'unigram_like_frequency',
       'unigram_people_frequency', 'unigram_know_frequency',
       'unigram_time_frequency', 'unigram_really_frequency',
       'unigram_ive_frequency', 'unigram_even_frequency',
       'unigram_much_frequency',
       ...
       'empath_musical', 'empath_neglect', 'empath_surprise', 'empath_ship',
       'empath_worship', 'season_0_feature', 'season_1_feature',
       'season_2_feature', 'season_3_feature', 'class'],
      dtype='object', length=258)
27


uid  unigram_im_frequency  unigram_like_frequency  \
0    train_subject2077              0.004101                0.008434   
1    train_subject9419              0.009185                0.009185   
2    train_subject6353              0.012346                0.004938   
3    train_subject8735              0.008364                0.013068   
4    train_subject6921              0.009517                0.005124   
..                 ...                   ...                     ...   
481  train_subject2252              0.010729                0.009073   
482  train_subject2415              0.022473                0.013128   
483  train_subject1201              0.011389                0.007217   
484  train_subject4879              0.007115                0.006468   
485  train_subject2219              0.009032                0.011097   

     unigram_people_frequency  unigram_know_frequency  unigram_time_frequency  \
0                    0.008937                0.002399                0.003792   
1                    0.013777                0.005741                0.001148   
2                    0.000000                0.000000                0.004938   
3                    0.010978                0.007841                0.004705   
4                    0.001464                0.004392                0.000732   
..                        ...                     ...                     ...   
481                  0.005762                0.004040                0.006424   
482                  0.005406                0.011352                0.005329   
483                  0.001353                0.004623                0.006202   
484                  0.003234                0.008409                0.003234   
485                  0.002194                0.003355                0.003484   

     unigram_really_frequency  unigram_ive_frequency  unigram_even_frequency  \
0                    0.003018               0.001315                0.003443   
1                    0.002296               0.005741                0.004592   
2                    0.000000               0.000000                0.000000   
3                    0.003136               0.002091                0.000523   
4                    0.001464               0.004392                0.003660   
..                        ...                    ...                     ...   
481                  0.001722               0.004106                0.004239   
482                  0.009113               0.004479                0.003784   
483                  0.002706               0.004172                0.003383   
484                  0.007762               0.000000                0.000647   
485                  0.006323               0.004000                0.002710   

     unigram_much_frequency  ...  unigram_though_frequency  \
0                  0.002786  ...                  0.001238   
1                  0.004592  ...                  0.003444   
2                  0.000000  ...                  0.000000   
3                  0.001568  ...                  0.002091   
4                  0.005124  ...                  0.001464   
..                      ...  ...                       ...   
481                0.003643  ...                  0.001590   
482                0.008572  ...                  0.002162   
483                0.002594  ...                  0.002255   
484                0.005821  ...                  0.000000   
485                0.002968  ...                  0.001419   

     unigram_help_frequency  adjective_frequency  verb_frequency  \
0                  0.000812             0.071422        0.160079   
1                  0.000000             0.069710        0.164458   
2                  0.000000             0.062500        0.130208   
3                  0.002614             0.057740        0.169625   
4                  0.003660             0.067878        0.160782   
..                      ...                  ...             ...   

In [31]:
KF = KFold(10,True,1)
for group in groups:
    train = df.drop(df.columns[group],axis=1)
    

240
------
254
------
255
------
257
------
257
------
256
------
253
------
255
------
253
------
254
------
250
------
257
------
257
------
255
------
255
------
64
------


In [20]:
df.drop(df.columns[g1],axis=1)

uid  adjective_frequency  verb_frequency  noun_frequency  \
0    test_subject7776             0.056317        0.157095        0.230826   
1    test_subject9710             0.036765        0.198529        0.220588   
2    test_subject5525             0.060198        0.161521        0.218455   
3    test_subject1620             0.104101        0.148265        0.203470   
4    test_subject2990             0.016807        0.151261        0.369748   
..                ...                  ...             ...             ...   
396  test_subject9802             0.062066        0.166336        0.198113   
397  test_subject8945             0.023810        0.178571        0.309524   
398  test_subject2751             0.077523        0.136316        0.260146   
399  test_subject1448             0.064417        0.156442        0.220859   
400   test_subject937             0.063029        0.162241        0.263496   

     adverb_frequency  negation_frequency  punctuation_frequency  \
0            0.049278            0.005558               0.019266   
1            0.102941            0.000000               0.029412   
2            0.045478            0.008019               0.017641   
3            0.048896            0.009464               0.003155   
4            0.025210            0.000000               0.042017   
..                ...                 ...                    ...   
396          0.059086            0.007448               0.027309   
397          0.023810            0.000000               0.023810   
398          0.057232            0.006764               0.007804   
399          0.052147            0.006135               0.024540   
400          0.044645            0.006128               0.031806   

     emoticon_frequency  capital_frequency  avg_comments_number  ...  \
0              0.005222           0.060022                   88  ...   
1              0.000000           0.007353                    4  ...   
2              0.000344           0.032648                  131  ...   
3              0.000000           0.050473                    2  ...   
4              0.010870           0.050420                    3  ...   
..                  ...                ...                  ...  ...   
396            0.001775           0.036246                   53  ...   
397            0.000000           0.000000                    4  ...   
398            0.000000           0.029657                   16  ...   
399            0.003584           0.024540                    9  ...   
400            0.000328           0.028596                   33  ...   

     empath_musical  empath_neglect  empath_surprise  empath_ship  \
0          0.003940        0.000438         0.000000     0.000876   
1          0.000000        0.000000         0.000000     0.008065   
2          0.002207        0.000000         0.000207     0.000207   
3          0.000000        0.005272         0.000000     0.000000   
4          0.032967        0.000000         0.000000     0.000000   
..              ...             ...              ...          ...   
396        0.001186        0.000000         0.000000     0.000000   
397        0.000000        0.000000         0.000000     0.000000   
398        0.006619        0.000000         0.001805     0.001203   
399        0.003584        0.000000         0.000000     0.000000   
400        0.001311        0.000328         0.000000     0.000328   

     empath_worship  season_0_feature  season_1_feature  season_2_feature  \
0          0.000000          0.009174          0.009258          0.990484   
1          0.000000          0.000000          0.500000          0.000000   
2          0.000552          0.106952          0.113700          0.688163   
3          0.000000          1.000000          0.000000          0.000000   
4          0.000000          0.000000          0.000000          0.000000   
..              ...               ...               ...               ...   
396        0.000000          1.

In [70]:
d = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6]
k = KFold(3,True,2)

In [72]:
# enumerate splits
for tr, te in k.split(d):
	print('train: %s, test: %s' % (tr, te))

train: [0 2 3 5], test: [1 4]
train: [0 1 4 5], test: [2 3]
train: [1 2 3 4], test: [0 5]


In [32]:
test_data_path = '/projets/sig/mullah/nlp/depression/features/2017/test/test_eRisk_depression_2017_1.csv'
test_data = pd.read_csv(test_data_path)
test_data

uid  unigram_im_frequency  unigram_like_frequency  \
0    test_subject7776              0.011226                0.012953   
1    test_subject9710              0.000000                0.000000   
2    test_subject5525              0.004755                0.007831   
3    test_subject1620              0.006873                0.003436   
4    test_subject2990              0.000000                0.000000   
..                ...                   ...                     ...   
396  test_subject9802              0.007481                0.006234   
397  test_subject8945              0.000000                0.000000   
398  test_subject2751              0.002130                0.008520   
399  test_subject1448              0.000000                0.015267   
400   test_subject937              0.004380                0.006884   

     unigram_people_frequency  unigram_know_frequency  unigram_time_frequency  \
0                    0.005181                0.005181                0.001727   
1                    0.000000                0.000000                0.015385   
2                    0.004615                0.008111                0.003076   
3                    0.000000                0.006873                0.003436   
4                    0.000000                0.000000                0.000000   
..                        ...                     ...                     ...   
396                  0.007481                0.002494                0.006234   
397                  0.026316                0.000000                0.000000   
398                  0.002130                0.002130                0.012780   
399                  0.007634                0.015267                0.000000   
400                  0.002503                0.006258                0.003129   

     unigram_really_frequency  unigram_ive_frequency  unigram_even_frequency  \
0                    0.002591               0.001727                0.000864   
1                    0.015385               0.000000                0.000000   
2                    0.003076               0.002657                0.001958   
3                    0.000000               0.013746                0.003436   
4                    0.000000               0.000000                0.000000   
..                        ...                    ...                     ...   
396                  0.011222               0.002494                0.003741   
397                  0.000000               0.000000                0.000000   
398                  0.004260               0.008520                0.001065   
399                  0.007634               0.000000                0.000000   
400                  0.000626               0.002503                0.000000   

     unigram_much_frequency  ...  empath_musical  empath_neglect  \
0                  0.003454  ...        0.003940        0.000438   
1                  0.015385  ...        0.000000        0.000000   
2                  0.001538  ...        0.002207        0.000000   
3                  0.003436  ...        0.000000        0.005272   
4                  0.000000  ...        0.032967        0.000000   
..                      ...  ...             ...             ...   
396                0.002494  ...        0.001186        0.000000   
397                0.000000  ...        0.000000        0.000000   
398                0.004260  ...        0.006619        0.000000   
399                0.000000  ...        0.003584        0.000000   
400                0.002503  ...        0.001311        0.000328   

     empath_surprise  empath_ship  empath_worship  season_0_feature  \
0           0.000000     0.000876        0.000000          0.009174   
1           0.000000     0.008065        0.000000          0.000000   
2           0.000207     0.000207        0.000552          0.106952   
3           0.000000     0.000000        0.000000          1.000000   
4           0.000000     0.000000        0.000000          