In [8]:
import os
import sys
import pandas as pd
from functools import cmp_to_key

def cmp(x, y):
    if len(x)<len(y):
        return -1
    elif len(x)==len(y):
        if x<y:
            return -1
        elif x == y:
            return 0
        else:
            return 1
    else:
        return 1


#folder_path = '/projets/sig/mullah/nlp/depression/features/2017/train'
folder_path = '/projets/sig/mullah/nlp/depression/features/2017/test'
#print (folder_path)

test_filenames = ['test_eRisk_depression_'+str(i)+'.csv' for i in range(1, 11)]
#print (test_filenames)
test_filenames.sort(key=cmp_to_key(cmp))
print (test_filenames)

'''
for fileno in range(0, len(filenames)-1):
    filename = filenames[fileno]
    print (filename)
    
filename = filenames[len(filenames)-1]
print (filename)
prediction_dir = '/projets/sig/mullah/nlp/depression/prediction/2017'
feature_acro = 'All'
approach = 'random_forest' + '_' + 'natural'
filename='test_eRisk_depression_1.csv'
prediction_file = os.path.join(prediction_dir,'test',feature_acro,filename[:-4]+"_"+approach+".txt")

data = pd.read_csv(prediction_file, sep='\t', header=None)
uid = data[0]
scores = data[1]
print (scores)
decisions = [1 if score>=0.5 else 0 for score in scores]
print (decisions)
dd = pd.DataFrame(list(zip(uid, decisions)))
dd
'''

['test_eRisk_depression_1.csv', 'test_eRisk_depression_2.csv', 'test_eRisk_depression_3.csv', 'test_eRisk_depression_4.csv', 'test_eRisk_depression_5.csv', 'test_eRisk_depression_6.csv', 'test_eRisk_depression_7.csv', 'test_eRisk_depression_8.csv', 'test_eRisk_depression_9.csv', 'test_eRisk_depression_10.csv']


'\nfor fileno in range(0, len(filenames)-1):\n    filename = filenames[fileno]\n    print (filename)\n    \nfilename = filenames[len(filenames)-1]\nprint (filename)\nprediction_dir = \'/projets/sig/mullah/nlp/depression/prediction/2017\'\nfeature_acro = \'All\'\napproach = \'random_forest\' + \'_\' + \'natural\'\nfilename=\'test_eRisk_depression_1.csv\'\nprediction_file = os.path.join(prediction_dir,\'test\',feature_acro,filename[:-4]+"_"+approach+".txt")\n\ndata = pd.read_csv(prediction_file, sep=\'\t\', header=None)\nuid = data[0]\nscores = data[1]\nprint (scores)\ndecisions = [1 if score>=0.5 else 0 for score in scores]\nprint (decisions)\ndd = pd.DataFrame(list(zip(uid, decisions)))\ndd\n'

In [3]:
import pandas as pd

data = pd.read_csv('/projets/sig/mullah/nlp/depression/features/2017/train/ch2_fs/train_eRisk_depression.csv')
data

uid  frequency_of_depress  empath_sadness  \
0    train_subject2077              0.000706        0.001353   
1    train_subject9419              0.000000        0.000557   
2    train_subject6353              0.000000        0.001309   
3    train_subject8735              0.000000        0.001782   
4    train_subject6921              0.000000        0.000000   
..                 ...                   ...             ...   
481  train_subject2252              0.002708        0.001170   
482  train_subject2415              0.005632        0.001665   
483  train_subject1201              0.005659        0.001598   
484  train_subject4879              0.000000        0.000000   
485  train_subject2219              0.003269        0.001350   

     unigram_feel_frequency  frequency_of_Myself  empath_contentment  \
0                  0.001586             0.000595            0.001055   
1                  0.001148             0.002759            0.000557   
2                  0.002469             0.000000            0.001309   
3                  0.003136             0.002530            0.001782   
4                  0.001464             0.000937            0.000776   
..                      ...                  ...                 ...   
481                0.002450             0.006799            0.001397   
482                0.007568             0.012548            0.003872   
483                0.003045             0.001990            0.001918   
484                0.000647             0.000929            0.000973   
485                0.001290             0.002834            0.001157   

     empath_shame  noun_frequency  empath_nervousness  empath_pain  ...  \
0        0.002547        0.225595            0.001294     0.003642  ...   
1        0.000557        0.198822            0.001114     0.000557  ...   
2        0.002618        0.332031            0.001309     0.002618  ...   
3        0.004073        0.223321            0.002037     0.003055  ...   
4        0.001165        0.218718            0.001165     0.001165  ...   
..            ...             ...                 ...          ...  ...   
481      0.002144        0.207506            0.001917     0.003282  ...   
482      0.005066        0.151618            0.005645     0.006442  ...   
483      0.002930        0.179275            0.002877     0.003942  ...   
484      0.000649        0.224591            0.000973     0.001298  ...   
485      0.002122        0.237165            0.001350     0.003215  ...   

     min_post_number  empath_party  empath_leader  empath_driving  \
0                 11      0.002567       0.001493        0.002587   
1                  0      0.001671       0.003900        0.000000   
2                  2      0.001309       0.000000        0.002618   
3                  2      0.003055       0.000764        0.000764   
4                  0      0.001165       0.000388        0.004658   
..               ...           ...            ...             ...   
481                7      0.004256       0.000910        0.000715   
482                5      0.002678       0.000688        0.000253   
483                0      0.003516       0.001172        0.000746   
484                1      0.003569       0.000973        0.000000   
485                2      0.004373       0.000900        0.000965   

     empath_crime  negation_frequency  linsear_write_formula  \
0        0.005592            0.009938               6.315958   
1        0.000000            0.006382               9.777778   
2        0.000000            0.009115               2.606303   
3        0.000509            0.005841               3.360627   
4        0.000000            0.007542               5.213960   
..            ...                 ...                    ...   
481      0.001722            0.008463               4.928003   
482      0.000181            0.010684               3.803517   
483      0.001864            0.011836               3.559284   
484      0.0006

In [35]:
import pandas as pd

d = [[1, 2], [3, 4]]
df1 = pd.DataFrame(data=d)
#print (df1)
df1.columns = ['a', 'b']
#print (df1)

d_all = df1
#print (d_all)

d = [[3, 25], [1, 14]]
df2 = pd.DataFrame(data=d)
#print (df2)
df2.columns = ['a', 'c']
#print (df2)

d_all = pd.merge(d_all, df2, on='a')
#print (d_all)

d = [[1, 20], [3, 240]]
df3 = pd.DataFrame(data=d)
df3.columns = ['a', 'd']
#print (df3)
d_all = pd.merge(d_all, df3, on='a')
#print (d_all)
#print (d_all)
columns = [1, 2, 3]
preds = d_all.filter(d_all.columns[columns], axis=1)

preds_np = preds.to_numpy()
print (preds_np)
print (preds_np[0])
print (preds_np[1])

[[  2  14  20]
 [  4  25 240]]
[ 2 14 20]
[  4  25 240]


In [34]:
import tensorflow as tf
import torch
import numpy as np
from transformers import BertTokenizer, BertModel
from torch.utils.data import (DataLoader, RandomSampler, SequentialSampler,
                              TensorDataset)

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')
model.eval()
bert_layers = [-1, -2, -3, -4]

text = "Replace me by any text you'd like."
encoded_input = tokenizer(text, pad_to_max_length=True,truncation=True, truncation_strategy='only_first', max_length=512, return_tensors='pt')
output = model(**encoded_input)
vectors = []
for ldx in bert_layers:
    vectors.append(output[0][0][ldx].detach().cpu().numpy())
print (vectors)
text_vect = np.mean(vectors, axis=0)
print (text_vect)
#print (output[0][0][0])
#print (len(output[0][0][0]))

[array([ 2.37983599e-01, -2.96372980e-01,  5.11597574e-01,  2.88620919e-01,
       -8.11915565e-03, -1.29475445e-01,  3.24096084e-01,  5.55316269e-01,
        3.47905189e-01, -2.41869643e-01, -2.57321566e-01,  1.00632198e-01,
       -4.59065475e-02,  2.29496837e-01,  1.70846134e-01,  7.94668272e-02,
       -2.11360767e-01,  4.56847697e-01,  1.00413524e-01, -1.90477178e-01,
        5.60739124e-03,  2.41107233e-02, -2.18137518e-01, -1.85297370e-01,
        3.77735168e-01,  2.91523337e-01, -1.06547251e-01, -1.13946907e-01,
       -3.24287981e-01,  2.17954323e-01,  2.58243680e-01,  6.10546358e-02,
        4.94534150e-02,  1.39723346e-01, -4.70639646e-01,  1.84277147e-01,
       -8.34998395e-03, -1.26891226e-01,  1.24471270e-01, -5.04317228e-03,
       -2.22332194e-01, -4.48809832e-01, -2.43380606e-01, -1.20261209e-02,
        6.63142884e-03, -1.52418002e-01, -1.01463206e-03, -6.69208586e-01,
       -3.00997440e-02,  2.22118273e-01, -1.33577138e-01, -3.83876599e-02,
       -4.26736087e-01, 

In [8]:
input_ids = torch.tensor(tokenizer.encode(text, pad_to_max_length=True, truncation_strategy='only_first', max_length=512)).unsqueeze(0)  # Batch size 1
with torch.no_grad():
    outputs = model(input_ids)
print (len(outputs[0][0][0].detach().cpu().numpy()))
print (outputs[0][0][0].detach().cpu().numpy())


Truncation was not explicitely activated but `max_length` is provided a specific value, please use `truncation=True` to explicitely truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


768
[-3.42553973e-01  4.96099591e-01  1.76289886e-01  5.84073126e-01
 -4.70345825e-01 -2.67480373e-01  1.00713658e+00 -2.01292545e-01
  1.37731269e-01  3.82893622e-01  2.85590380e-01 -5.05305469e-01
 -2.39328399e-01  6.57257438e-01  3.99443984e-01  7.41737664e-01
 -3.50847036e-01  5.25797248e-01 -2.72031158e-01  4.70898151e-01
  5.80170095e-01  1.04132831e-01  8.73645961e-01  2.83713713e-02
 -1.63299903e-01  4.63758707e-01 -3.48091960e-01 -1.36079180e+00
 -6.80526853e-01 -8.61379653e-02 -7.53003120e-01  4.18499172e-01
  2.87635267e-01 -3.06830078e-01  2.83240229e-01 -4.84991670e-01
 -2.90224105e-01  7.91893806e-03  9.41970646e-01  3.11956480e-02
 -2.96296060e-01 -5.48897028e-01  6.37769639e-01 -5.17120600e-01
 -1.69835147e-02 -6.64578855e-01 -3.20522904e+00  2.24338353e-01
 -1.33264139e-01 -1.03447580e+00  1.58329755e-02 -4.51136857e-01
  4.09753382e-01  3.88072848e-01 -2.18098983e-02  4.69898790e-01
  5.57930768e-01 -1.16056359e+00  1.60272586e+00 -2.01475158e-01
 -3.33641320e-01  6.2

In [3]:
import numpy as np

a = [2, 5, 9, 11, 25, 100, 99]
np.sum(np.asarray(a)>50)

2

In [ ]:
import torch
print (torch.__version__)